### ISSUE TITLE
Client Infinitely Hangs Following Memcached Server Reset

### ISSUE THREAD

**Issue by Hobray** [cnblogs/EnyimMemcachedCore#77]
When running a dotnet core application with the EnyimMemcached client service registered, if one of the connected servers is stopped and restarted, the IMemcachedClient instance hangs infinitely when calling **StoreAsync** on the client instance. The last log that comes from from Enyim.Caching.Configuration.MemcachedClientConfiguration  is "Socket was reset. (socket GUID)".

Here's the easiest way to reproduce the problem

- Create a local Memcached Docker container by running the command **docker run --name my-memcache -p 127.0.0.1:11211:11211 -d memcached memcached -m 64**
- Create a new dotnet core web application
- Add the EnyimMemcachedCore NuGet package to the application
- Register the EnyinMemcached service in the **Startup.cs**. This is how I'm doing it in mine:

````
public void ConfigureServices(IServiceCollection services)
{
    ...
    services.AddEnyimMemcached((cacheConfig) =>
    {
        //Add servers (point to Docker container on the port forwarded to localhost)
        cacheConfig.AddServer("127.0.0.1", 11211);
    });
    ...
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
    ...
    app.UseEnyimMemcached();
    ...
}
````

- Now write a controller that takes and **IMemcachedClient** constructor parameter
- In the controller add an implementation that makes a call to the IMemcachedClient **StoreAsync** method
- Run the application and make sure everything is wired and working properly
- Now run the **docker stop my-memcache** command to stop the Memcached Docker container then run **docker start my-memcache** to get it running again
- Without ever shutting down the dotnet core application, go back and re-execute the method that calls **StoreAsync**
- The logger will write a log indicating that Enyim.Caching.Configuration.MemcachedClientConfiguration is "Aquiring stream from pool..." and then another message will log saying that "Socket (GUID) was reset". After that it will write a log of "Socket was reset. (GUID)".
At this point the request (and any subsequent session requests) will be hung indefinitely. The only thing that can be done is to restart the application.

**Comment by cnblogs-dudu** [comment]
Sorry. This issue has been fixed in 2.2.0-beta5. Please try it.

**Comment by cnblogs-dudu** [comment]
It has been really fixed in 2.2.0.

**Comment by kylerudy-imvu** [comment]
We're still experiencing this behavior when running a text mode connection on Ubuntu Trusty and Ubuntu Bionic. A server restart results in an endless loop of PooledSocket:;ReadByte() calls from TextSocketHelper::ReadLine(). This results in high CPU usage and an endless allocation of memory, due to the unchecked use of MemoryStream. Since we restart one of our memcached servers every day at 8 AM, I took the opportunity of inspecting with lldb this time.

First, an excerpt near the top of perf top:
```
3.00%  perf-24389.map                                         [.] Interop/Error /* MT: 0x00007FFF7E2FD9A8 */ [System.IO.FileSystem] dynamicClass::IL_STUB_PInvoke(native int,Interop/Sys/MessageHeader /* MT: 0x00007F1
2.79%  perf-24389.map                                         [.] instance int32 [EnyimMemcachedCore] Enyim.Caching.Memcached.PooledSocket::ReadByte()
```

sos DumpHeap showed that the vast majority of used memory was System.Byte[], particularly this one:
`00007ffa4e835020 00007fff7cd6a0e8 268435480`

Further inspection:
```
Name:        System.Byte[]
MethodTable: 00007fff7cd6a0e8
EEClass:     00007fff7c4e8030
Size:        268435480(0x10000018) bytes
Array:       Rank 1, Number of elements 268435456, Type Byte
Content:     ................................................................................................................................
Fields:
None

(lldb) sos GCRoot 00007ffa8bfff020
Thread 62d7:
    00007FFAE37F9AF0 00007FFF8089EF70 Enyim.Caching.Memcached.Protocol.Text.TextSocketHelper.ReadLine(Enyim.Caching.Memcached.PooledSocket)
        r14:
            ->  00007FFD3024ECC8 System.IO.MemoryStream
            ->  00007FFA8BFFF020 System.Byte[]
```

As for the values in the Byte[], towards the end we see uninitialized 0, as we'd expect from MemoryStream. The beginning and middle are all filled with byte vals of 255.

That's all I have for you at the moment. I'm going to clone the repo, modify the code to add some sanity checks and additional output (I'm still pretty clumsy with lldb and sos), then hopefully update you with how and why this NetworkStream to a text-mode memcached socket is providing endless 255's.

**Comment by kylerudy-imvu** [comment]
When I pulled down a copy of the repository at latest master and added output to it, I found that the bug no longer reproduces when we restart one of our servers. Since we were using nuget latest stable, 2.2.3, I'm led to wonder if a mistake was made in publishing. I suppose I'll continue to monitor over the weekend, in case this is intermittent.

**Comment by cnblogs-dudu** [comment]
@kylerudy-imvu Fixed in 2.2.4.
